name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    strategy:
      matrix:
        target:
          - linux/amd64
          - linux/arm64
          - linux/riscv64
    name: build-docker, ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.target }}
          push: true
          tags: ghcr.io/bekcpear/gentoo-env:latest
