name: build

on:
  workflow_dispatch:
    inputs:
      platforms:
          description: 'The platforms to build (seperated by comma), default to all.'
          required: false
          type: string
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron: '0 3 * * 1'

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-target-platforms:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup matrix
        id: set-matrix
        shell: bash
        run: |
          ./.github/scripts/prepare-platforms.sh "${{ inputs.platforms }}" "${{ github.event_name }}"
  build-docker:
    needs: prepare-target-platforms
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-target-platforms.outputs.matrix) }}
    name: build-docker, ${{ matrix.target }}
    runs-on: ${{ matrix.runson }}
    env:
      IMAGE_NAME: ghcr.io/bekcpear/gentoo-env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate architecture tag
        id: arch-tag
        env:
          TAG_NAME: ${{ matrix.target }}
        run: |
          echo "tag=${TAG_NAME##*/}" >>$GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >>$GITHUB_OUTPUT
      - name: Build and load
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.target }}
          load: true
          tags: ${{ steps.arch-tag.outputs.image_name }}:${{ steps.arch-tag.outputs.tag }}
      - name: Push and re-tag to the :latest
        shell: bash
        run: |
          ./.github/scripts/push.sh
