name: build

on:
  workflow_dispatch:
    inputs:
      platforms:
          description: 'The platforms to build (seperated by comma), default to all.'
          required: false
          type: string
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron: '0 3 * * 1'

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-target-platforms:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup matrix
        id: set-matrix
        shell: bash
        run: |
          ./.github/scripts/prepare-platforms.sh "${{ inputs.platforms }}"
  build-docker:
    needs: prepare-target-platforms
    strategy:
      matrix: ${{ fromJson(needs.prepare-target-platforms.outputs.matrix) }}
    name: build-docker, ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.target }}
          push: true
          tags: ghcr.io/bekcpear/gentoo-env:latest
